### PR TITLE
Week 02

### PR DESCRIPTION
**Pull request by cjfernanders1986**

### CODE REVIEW

**Comment by cheuschober** [comment]
@cjfernanders1986 You should have received an invitation from GitHub to join this organization.

**Comment by cheuschober** [comment]
ok to test

**Comment by cjfernanders1986** [comment]
I made some mistakes that I want to fix is that ok?

**Comment by cheuschober** [comment]
@cjfernanders1986 In the future, please don't open multiple pull requests for the same work. Additionally, pull requests must be made against branches named after your github username.

**Pull request closed without merging**
