### PR TITLE
Warmup Pull Request for week 2

### PR DESCRIPTION
**Pull request by Shinseeker**
I ran tests and made sure was accurate before pulling the request.

### CODE REVIEW

**Comment by Shinseeker** [comment]
Hi Chad,

I was not feeling Task 5. I had to do that one task several time lol. Before even trying to do a pull request i ran all the test that you mentioned in your lectures. Also if there is anything wrong with them how can i use the same pull request.

**Comment by cheuschober** [comment]
If you wish to continue making changes to your assignment, with a pull request still open, all you need to do is `git commit` your work and `git push` like you would do for the first submission. The new changes will automatically appear in the first pull request you opened.

**Comment by cheuschober** [comment]
ok to test

**Comment by Shinseeker** [comment]
Danke schoen!

**Pull request merged**
